name: svejcar-dev
version: 1.4.5.0
github: "vaclavsvejcar/svejcar-dev"
license: Apache-2.0
author: "Vaclav Svejcar"
maintainer: "vaclav.svejcar@gmail.com"
copyright: "2019-2020 Vaclav Svejcar"

dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  site:
    main: Site.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blaze-html
      - bytestring
      - containers
      - data-default-class
      - directory
      - filepath
      - hakyll
      - hakyll-sass
      - language-javascript
      - lens
      - pandoc
      - pandoc-types
      - pretty-terminal
      - skylighting
      - skylighting-core
      - split
      - text
      - time
      - xml
