resolver: lts-17.5

extra-package-dbs: []

flags: {}

packages:
  - "."

extra-deps:
  - hakyll-4.13.4.1
  - hakyll-sass-0.2.4
  - hlibsass-0.1.10.1
  - hsass-0.8.0
  - pandoc-citeproc-0.17.0.2

allow-newer: true
